language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "pypy"
env:
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.4.3
install:
  - pip install Django==$DJANGO_VERSION
  - python setup.py install
script: python setup.py test
